name: mboa_waste
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  easy_loading: ^0.0.4
  equatable: ^2.0.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  fl_chart: ^0.41.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_easyloading: ^3.0.3
  flutterfire_ui: ^0.3.1
  google_fonts: ^2.2.0
  google_maps_flutter: ^2.1.2
  hooks_riverpod: ^1.0.3
  iconsax: ^0.0.8
  line_icons: ^2.0.1
  reactive_forms: ^11.0.1
  persistent_bottom_nav_bar: ^4.0.2
  riverpod: ^1.0.3
  flutter_native_splash: ^2.1.2
  


flutter_native_splash: 
  background_image: assets/images/splash_screen.png

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
